// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgxnopaolpcpusimsrby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNneG5vcGFvbHBjcHVzaW1zcmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjM4NzAsImV4cCI6MjA3MTE5OTg3MH0.STGvAYkNLyY6vw63T3ygHH-KyU5RZnsfsCTw3Hy4-ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});